version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
      POSTGRES_DB: ivolanitra_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: Docker/FastAPI/
    restart: always
    volumes:
      - .:.
    ports:
      - 8087:8087